#+TITLE: System Installation Guide
#+AUTHOR: illadetagomago@gmail.com

* What is this for?
This document provide needed system setting and packages for gnu/linux system.
** Packages
Most of packages are fine with apt, but some of debian packages are old that induces some unwanted bugs.
So some packages need build-install from their official websites, they are seperated by checkboxs.
*** apt packages
This is list of package viable with using apt install.
1) [ ] i3: i3wm is now my primal window manager. i3's config file is located at
   ~/.config/i3/config and it is included in this repository.
2) [ ] network-manager: NetworkManager is used for connecting wifi. See more info with man nmcli.
   WARNING: Make sure to wipe any existing network interface information excep lo located at
   /etc/network/interface. Otherwise, network manager would not work on such interfaces.
3) [ ] vim: Used for lightweight text editing.
4) [ ] git: Used for version control and such.
5) [ ] build-essential: Literally.
6) [ ] xinit: Used for starting i3 when credential was met. To avoid this behavior,
   try C-M-F2 on login screen.
7) [ ] rxvt-unicode: Replacement of xterm or gnome-terminal.
8) [ ] ibus: Used for typing korean, needs configuration by using ibus-setup,
   which needs some configuration at .bash_profile or .bashrc.
9) [ ] ibus-hangul: Also used for typing korean. Change Input Method to Korean,
   and change preference of Korean by checking Commit in word unit and change Toggle key.
10) [ ] tlp: Used for battery management for laptop. Make sure to enable it after install,
    by sudo tlp start. Check [[https://linrunner.de/tlp/usage/index.html][wiki]] for more info.
11) [ ] tlp-rdw: Used for battery management with radio device managing.
    Might disable bluetooth on battery when booted.
12) [ ] gh: Used for getting credential infomation on github.com.
    Could use private-token for alternative method.
13) [ ] nitrogen: Used for getting background on i3wm.
14) [ ] firefox-esr: Web browser.
15) [ ] zip: Used for zipping.
16) [ ] unzip: Used for unzipping.
17) [ ] curl: Used for getting file or data.
18) [ ] wget: Used for getting file.
19) [ ] feh: Used for viewing image.
20) [ ] glibc-doc: Man pages for glibc.
21) [ ] manpages-dev: Man pages for basic C functions.
*** Manual install
This is list of packages that needs manual install. Some of depencies could be installed using apt.
1) [ ] emacs: Emacs needs manual build and install. Installation is well documented, but might need
   some options such as --with-x. [[https://www.gnu.org/software/emacs/][Official page]]
2) [ ] stow: Stow needs manual build and installed because of bugs regarding on --dotfiles option.
   It is well documented. [[https://www.gnu.org/software/stow/][Official page]]
3) [ ] picom: Picom needs manual install regarding on x11 and i3wm bug. Installation is well documented,
   but might need to install some build dependencies. [[https://github.com/yshui/picom][Official github page]]
4) [ ] bluetuith: bluetuith is not presented at apt. Installation is somewhat documented, but
   you need to install bluetooth and pulseaudio-module-bluetooth package via apt and install go
   manually. Also need to move or symlink executable located at ~/go/bin/ to /usr/bin/. [[https://darkhz.github.io/bluetuith/Installation.html][Official wiki]]
5) [ ] fastfetch: Looks cool.
6) [ ] dwm: Alternative windows manager. Need to install dmenu for full experience.
** System settings
- Make poweroff usable on regular user: Default debian setting puts poweroff on /usr/sbin/ which only
  allowed only by sudo. Copy poweroff at /usr/sbin/ to /usr/local/bin/ to allow user to access it.
- Install korean font: Default korean font on i3 or emacs is unbearable, Install NanumGothicCoding font
  at [[https://github.com/naver/nanumfont?tab=readme-ov-file][link]] and put this at ~/.local/share/fonts/.
- Creating Firefox private on dmenu: Copy firefox.desktop and create firefox-private.desktop file,
  edit Name to Firefox Private and also edit Exec to add option --private-window.
- Disable unused services: Check 'systemd-analyze blame' to get blueprint what is staggering your
  boot speed. On T440p, ModManager, NetworkManager-wait-online.service, and mei_me had to be disabled.
